# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv_transfer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kv_transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11kv_transfer.proto\x12\nkvtransfer\"J\n\rSendQueueItem\x12\x11\n\ttensor_id\x18\x01 \x01(\t\x12\x16\n\x0eremote_address\x18\x02 \x01(\t\x12\x0e\n\x06tensor\x18\x03 \x01(\x0c\"3\n\x07KVBatch\x12(\n\x05items\x18\x01 \x03(\x0b\x32\x19.kvtransfer.SendQueueItem\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32t\n\nKVTransfer\x12\x30\n\x08PutBatch\x12\x13.kvtransfer.KVBatch\x1a\x0f.kvtransfer.Ack\x12\x34\n\x08GetBatch\x12\x13.kvtransfer.KVBatch\x1a\x13.kvtransfer.KVBatchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDQUEUEITEM']._serialized_start=33
  _globals['_SENDQUEUEITEM']._serialized_end=107
  _globals['_KVBATCH']._serialized_start=109
  _globals['_KVBATCH']._serialized_end=160
  _globals['_ACK']._serialized_start=162
  _globals['_ACK']._serialized_end=184
  _globals['_KVTRANSFER']._serialized_start=186
  _globals['_KVTRANSFER']._serialized_end=302
# @@protoc_insertion_point(module_scope)
