# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kv_transfer_pb2 as kv__transfer__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kv_transfer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KVTransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutBatch = channel.unary_unary(
                '/kvtransfer.KVTransfer/PutBatch',
                request_serializer=kv__transfer__pb2.KVBatch.SerializeToString,
                response_deserializer=kv__transfer__pb2.Ack.FromString,
                _registered_method=True)
        self.GetBatch = channel.unary_unary(
                '/kvtransfer.KVTransfer/GetBatch',
                request_serializer=kv__transfer__pb2.KVBatch.SerializeToString,
                response_deserializer=kv__transfer__pb2.KVBatch.FromString,
                _registered_method=True)


class KVTransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PutBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PutBatch,
                    request_deserializer=kv__transfer__pb2.KVBatch.FromString,
                    response_serializer=kv__transfer__pb2.Ack.SerializeToString,
            ),
            'GetBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatch,
                    request_deserializer=kv__transfer__pb2.KVBatch.FromString,
                    response_serializer=kv__transfer__pb2.KVBatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvtransfer.KVTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvtransfer.KVTransfer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KVTransfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PutBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvtransfer.KVTransfer/PutBatch',
            kv__transfer__pb2.KVBatch.SerializeToString,
            kv__transfer__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvtransfer.KVTransfer/GetBatch',
            kv__transfer__pb2.KVBatch.SerializeToString,
            kv__transfer__pb2.KVBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
